# 3-best (Rust): rebuild std with size optimizations + immediate panic abort
[unstable]
build-std          = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort", "optimize_for_size"]

[build]
rustflags = [
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",
    "-Cpanic=abort",
    "-Cstrip=symbols",
]
